# Generated by Django 2.2.5 on 2020-03-22 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_auto_20200322_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='rooms.Photo'),
        ),
    ]
